# BLU10 - Learning Notebook - Part 1 of 3 - Framework

In [1]:
import numpy as np

# 1 Framework

Recommendation Systems (RS) are software systems that recommend items to users, that they might like.

We start by learning the main components of an RS.

![Recommender Sytems Framework](../media/recommender_systems_framework.png)

*Fig.1 - RS framework with a community, plus the basic and extended models.*

We refer back to this framework frequently throughout the specialization, but for now, let's drill down into each component.

## 1.1 Users

The *consumers* or people, denoted by $U = \{u_0, u_1, ..., u_m\}$, where $m \in \mathbb{N_0}$ and cardinality $\left\vert{U}\right\vert = m$.

We reserve the indexing letters $u$ and $v$ to denote generic individual users.

## 1.2 Items

The *products* or things, a set $I = \{i_0, i_1, ..., i_n\}$, with $n \in \mathbb{N_0}$ and number of elements $\left\vert{I}\right\vert = n$. 

The indexing letters for letters for items are $i$, $j$ and $l$.

## 1.3 Community

Users and items together form a shared space in which user opinions make sense.

The space of all possible ($u$, $i$) pairs is given by $U \times I = \{(u_0, i_0), (u_0, i_1), ..., (u_0, i_n), ..., (u_m, i_n)\}$.

The resulting set $U \times I$ contains $\left\vert{U}\right\vert * \left\vert{I}\right\vert = m * n$ possible combinations.

## 1.4 Ratings

The *transactions* or opinions, provided by the users about the items.

We write the set $R = \{r_{u_0, i_0}, ..., r_{u_m, i_n}\}$, where each rating $r_{u, i}$ corresponds to a user-item pair $(u, i) \in U \times I$.

We use $R'$ for the set of all recorded ratings, such as:

* Any user $u \in U$ can make no more than one rating $r_{u, i}$ for a particular item $i \in I$.
* Any user $u \in U$ is free to rate, or not, any number of items $i \in I$, including none.

Formally, the set of stored ratings $R' \subseteq R$. (The set of stored ratings $R'$ is a subset of the set containing all possible ratings $R$.)

In practice, if $R'$ is not a strict subset of $R$, i.e., if $R' \subset R$, you don't need an RS.

## 1.5 Base model

The essential components, known as the fundamental entities.

## 1.6 Profiles

Profiles are a collection of objects (users or items, in our framework) and their attributes.

Consider the set of attributes $A = \{a_0, ..., a_r\}$, where $r \in \mathbb{N_0}$. Let be $A$ an arbitrary set of item attributes.

We can define profiles $P = \{p_{i_0, a_0}, ..., p_{i_n, a_r}\}$, where $(i, a) \in I \times A$ and values $p_{i, a}$ indicate the presence of $a$ in $i$.

Let be $B$ be an arbitrary set of user characteristics, and we can apply the same reasoning to build user profiles.

Typically, item profiles contain information about the content of the items, and user profiles are more focused on demographics.

## 1.7 User model

As introduced above, RS are in the business of matching users and items.

Sometimes, it's convenient to have user and item profiles in the same attribute space $A$.

The user model $M$, defines $M = \{m_{u_0, a_0}, ..., m_{u_m, a_r}\}$, for $(u, a) \in U \times A$, where $A$ is the set of item attributes.

## 1.8 Extended model

The extended model layer contains optional components which apply only to particular RS architectures.

# 2 Community matrix

This matrix is not a thing, as there's no community matrix: not in the literature, not anywhere. (Call it a thought experiment.)

We described our community as a finite set $U \times I = \{(u_0, i_0), (u_0, i_1), ..., (u_0, i_n), ..., (u_m, i_n)\}$.

Alternatively, the space of all possible user-item pairs $(u,i) \in U \times I$ can be represented as a $m$ x $n$ matrix:

$$\begin{bmatrix}(u_0, i_0) & (u_0, i_1) & ... & (u_0, i_n)\\ (u_1, i_0) & (u_1, i_1) & ... & (u_1, i_n)\\... & ... & ... & ...\\ (u_m, i_0) & (u_m, i_1) & ... & (u_m, i_n)\end{bmatrix}$$

Each row $u \times I$ is a user $u \in U$ and each column $U \times i$ is an item.

Growth means more users (rows) and items (columns), which is excellent for the community but bad on your servers.

# 3 Ratings matrix

The community matrix hints at the canonical representation of the ratings matrix, at the core of any RS.

We represent the set $R = \{r_{u_0, i_0}, ..., r_{u_m, i_n}\}$ as a $U \times I$  matrix, where the values are the ratings $r_{u, i}$, if they exist:

$$\begin{bmatrix}r_{u_0, i_0} & r_{u_0, i_1} & ... & r_{u_0, i_n}\\ r_{u_1, i_0} & r_{u_1, i_1} & ... & r_{u_1, i_n}\\... & ... & ... & ...\\ r_{u_m, i_0} & r_{u_m, i_1} & ... & r_{u_m, i_n}\end{bmatrix}$$

We represent not recorded ratings $r_{u, i} \notin R'$ as zeros or missing values, enforcing the $U \times I$ shape.

## 3.1 Sparsity

Keeping the entire community leads to large, very sparse rating matrices, as ratings are relatively rare.

We can compute the sparsity as the number of ratings missing among all possible ratings.

## 3.2 Important subsets

The subset of users that have rated an item $i \in I$ is given by $U_i \subseteq U$. 

We write $I_u \subseteq I$ the subset of items rated by user $u \in U$.

The subset items that have been rated by users $u, v \in U$ is $I_{u, v} \subseteq I$. 

Finally, $U_{i, j} \subseteq U$ is used for the subset of users that rated both items $i, j \in I$.

# 4 Creating a ratings matrix

## 4.1 Community matrix

As we know, the community matrix represents our entire community in a single matrix.

Take $U = \{Ana, Miguel, Beatriz\}$, and $I = \{Bananas, Water, Milk\}$. 

We represent $U \times I$, aka the community matrix, as:

$$\begin{bmatrix}(Ana, Bananas) & (Ana, Water) & (Ana, Milk)\\ (Miguel, Bananas) & (Miguel, Water) & (Miguel, Milk)\\ (Beatriz, Bananas) & (Beatriz, Water) & (Beatriz, Milk)\end{bmatrix}$$

However, as we already know, the community matrix is not a thing.

## 4.2 Types of data

Users manifest their opinion about an item in different ways.

### Explicit and implicit feedback

Feedback is said to be explicit when provided by the user and implicit if inferred based on user actions (e.g., clicks).

Implicit feedback usually takes the form of unary data,

### Rating scale

We write $S$ the set of possible ratings. For example, in 1-5 stars rating system $r_{u, i} \in S = \{1, 2, 3, 4, 5\}$.

| Type of data    | Description                          | Rating scale (examples) | Explicit/Implicit |  
|-----------------|--------------------------------------|-------------------------|-------------------|
| Numeric         | Continuous ratings                   | $S = [1, 5]$            | Explicit          |
| Ordinal         | Ordered categories                   | $S = \{1, 2, 3, 4, 5\}$ | Explicit          |
| Binary          | Good or bad  (e.g., Upvote/Downvote) | $S = \{-1, 1\}$         | Explicit          |
| Unary           | User action  (e.g., Click, Purchase) | $S = \{1\}$             | Implicit          |
*Table 1: Different types of data and rating scales*

## 4.3 Ratings matrix

Consider the following ratings matrix $R$, with $S = \{1, 2, 3, 4, 5\}$:

$$\begin{bmatrix}1 &  & 2\\ 1 & 5 & \\  & 2 & 1\end{bmatrix}$$

## 4.4 Representing vectors

Let's go bit by bit, starting with the first row of the matrix, corresponding to:

$$\begin{bmatrix}(Ana, Bananas) & (Ana, Water) & (Ana, Milk)\end{bmatrix}$$

To clarify, $I_{Ana} = \{Bananas, Milk\}$ and $(Ana, Bananas) \notin R'$. Right?

At the core of Numpy is the homogeneous (i.e., all elements of the same type) n-dimensional array.

Corresponding to the NumPy array:

```
┌───┬───┬───┐
│ 1 │   │ 2 │
└───┴───┴───┘
```

We can create using `numpy.array` with an array-like object, a standard Python list in this case.

In [2]:
np.array([1, np.NaN, 2])

array([ 1., nan,  2.])

The resulting array is what we call a rank-1 because it is a vector with one dimension.

Nonetheless, rank-1 arrays can be ambiguous, so we represent vectors as rank-2 arrays, i.e., as matrices with two dimensions.

The general convention is to use a column vector instead, i.e., a $n$ by 1 matrix, such as:

$$\begin{bmatrix}1 \\  \\ 2\end{bmatrix}$$

Corresponding to a 3 by 1 matrix, such as:

```
┌───┐
│ 1 │
├───┤
│   │
├───┤
│ 2 │
└───┘
```

We do this by using a list of lists, with one nested list per row.

In [3]:
np.array([[1], [np.NaN], [2]])

array([[ 1.],
       [nan],
       [ 2.]])

## 4.5 Representing matrices

Finally, we create our ratings matrix $R$, corresponding to:
```
┌───┬───┬───┐
│ 1 │   │ 2 │
├───┼───┼───┤
│ 1 │ 5 │   │
├───┼───┼───┤
│   │ 2 │ 1 │
└───┴───┴───┘
```

Conveniently, we can pass a list of lists, just like we did above.

In [4]:
R = [[1, np.NaN, 2], [1, 5, np.NaN], [np.NaN, 2, 1]]
R = np.array(R)
R

array([[ 1., nan,  2.],
       [ 1.,  5., nan],
       [nan,  2.,  1.]])

## 4.6 Matrix attributes

Some important attributes of any `ndarray`, to keep in mind.

In [5]:
ndims = R.ndim
nrows = R.shape[0]
ncols = R.shape[0] 
dtype = R.dtype

print("R is a {}-dimensional, {} by {} matrix, of {} elements.".format(ndims, nrows, ncols, dtype))

R is a 2-dimensional, 3 by 3 matrix, of float64 elements.


## 4.7 Saving the matrix

We can save the matrix to a binary file in NumPy `.npy` format.

Note that `save` is a stand-alone function and not an array method.

In [6]:
np.save('../data/interim/ratings_matrix', R)

Alternatively, we can dump the matrix into a `.csv` file, as we would typically do.

In [7]:
np.savetxt("../data/interim/ratings_matrix.csv", R, delimiter=",")

# 5 Prototyping ratings matrices

Let's prototype some different ratings matrices $R$, using the NumPy's [random sampling module](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html).

## 5.1 Numeric data

Perhaps the most popular of the random sampling methods is `rand`, which generates random values between 0 and 1 in a given shape.

In [8]:
np.random.rand(3, 3)

array([[0.93678268, 0.267354  , 0.21150915],
       [0.87369361, 0.49965834, 0.43313304],
       [0.44855671, 0.4806935 , 0.48229396]])

But now, consider  $S = [1, 5]$. How can you generate such a matrix?

We can call a method to draw samples from a `uniform` distribution.

In [9]:
np.random.uniform(low=1, high=5, size=(3, 3))

array([[3.89105499, 4.53467806, 4.35697619],
       [1.94887842, 1.45611082, 3.77513512],
       [1.4216611 , 1.91775071, 3.51133121]])

## 5.2 Discrete data

If we want a discrete, ordinal output, we can use `randint`, return random integers from low (inclusive) from high (exclusive).

It's perfect to generate ratings in the $S = \{1, 2, 3, 4, 5\}$.

In [10]:
np.random.randint(low=0, high=6, size=(3, 3))

array([[1, 5, 1],
       [2, 0, 5],
       [2, 0, 4]])

## 5.3 Binary data

The method `choice` is conventional to generate random samples from a given array.

Binary scale, $S = \{-1, 1\}$.

In [11]:
np.random.choice(a=[-1, 1], size=(3, 3))

array([[ 1,  1, -1],
       [ 1, -1,  1],
       [-1, -1,  1]])

## 5.4 Unary data

We can repeat the process to generate unary data.

In [12]:
np.random.choice(a=[0, 1], size=(3, 3))

array([[1, 1, 0],
       [0, 1, 0],
       [0, 1, 1]])

# 6 Recommendations

We need to fill in the blanks in our ratings matrix and return the best possible items to the user.

Throughout the course, we learn different ways to predict unseen ratings, but the outputs remain unchanged.

## 6.1 Prediction step

The RS core computation is to predict the utility of unseen items $i \in I \setminus I_u$ to a user $u$.

At the core, we learn a function $f$ that maps user-item pairs into ratings $f : U \times I \to S$ given by $\hat{r}_{u, i} = f(u, i)$.

Once we have it, there two main types of recommendations: top-$N$ and best-item.

## 6.2 Top-*K* items

For a given user $u \in U$, we need a set of predictions $\hat{R}_u = \{f(u, i) : (u, i) \in u \times (I \setminus I_u)\}$.

Then, we take a subset $L_u \subset (I \setminus I_u$), containing the items with the *k*-largest predicted ratings $\hat{r}_{u, i} \in \hat{R}_u$.

Optionally, $L_u = \{i_0, i_1, ..., i_k\}$ can be ordered as $\hat{r}_{u, i_0} \geq \hat{r}_{u, i_1} \geq ... \geq \hat{r}_{u, i_k}$.

## 6.3 Best-item

Can be seen as a particular case of top-$K$, with $K = 1$.

Thus, the function $f(u, i)$ can be used to find the best item, such as $j = \underset{i \space \in \space I \setminus I_u}{\mathrm{argmax}} \space f(u, i)$.

# 7 Context-awareness

Finally, some systems consider the context, alongside users and items. Take $C$ as a set of contexts.

The reasoning is that sometimes the utility for an item is observed to depend on other variables.

(A very good camera, for example, may be of lesser utility for a newbie than it is for pro, for example.)

In these cases, we need $f$ to use the context as well, as $f : U \times I \times C \to S$ given by $\hat{r}_{u, i, c} = f(u, i, c)$.

For a given user $u \in U$, the predictions become $\hat{R}_u = \{f(u, i, c) : (u, i, c) \in u \times (I \setminus I_u) \times C\}$.

## 7.1 Time

We can think of time as a particular case of context-aware RS, where $\hat{r}_{u, i, t} = f(u, i, t)$.